/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20Precompile } from "./IERC20Precompile";
export type { IPVM } from "./IPVM";
export type { IXcm } from "./IXcm";
export type { PVMark } from "./PVMark";
