/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPVMInterface extends Interface {
  getFunction(
    nameOrSignature: "hashLeaf" | "hashPair" | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "hashLeaf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hashPair",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "hashLeaf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashPair", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export interface IPVM extends BaseContract {
  connect(runner?: ContractRunner | null): IPVM;
  waitForDeployment(): Promise<this>;

  interface: IPVMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hashLeaf: TypedContractMethod<[leaf: BytesLike], [string], "view">;

  hashPair: TypedContractMethod<
    [left: BytesLike, right: BytesLike],
    [string],
    "view"
  >;

  verifyProof: TypedContractMethod<
    [leaf: BytesLike, proof: BytesLike[], root: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hashLeaf"
  ): TypedContractMethod<[leaf: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hashPair"
  ): TypedContractMethod<[left: BytesLike, right: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [leaf: BytesLike, proof: BytesLike[], root: BytesLike],
    [boolean],
    "view"
  >;

  filters: {};
}
