/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { IXcm, IXcmInterface } from "../../PVMark.sol/IXcm";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "dest",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "send",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IXcm__factory {
  static readonly abi = _abi;
  static createInterface(): IXcmInterface {
    return new Interface(_abi) as IXcmInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IXcm {
    return new Contract(address, _abi, runner) as unknown as IXcm;
  }
}
