/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC20Precompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Precompile__factory>;
    getContractFactory(
      name: "IPVM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IPVM__factory>;
    getContractFactory(
      name: "IXcm",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IXcm__factory>;
    getContractFactory(
      name: "PVMark",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PVMark__factory>;
    getContractFactory(
      name: "PVMarkPVM",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.PVMarkPVM__factory>;

    getContractAt(
      name: "IERC20Precompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Precompile>;
    getContractAt(
      name: "IPVM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IPVM>;
    getContractAt(
      name: "IXcm",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IXcm>;
    getContractAt(
      name: "PVMark",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PVMark>;
    getContractAt(
      name: "PVMarkPVM",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.PVMarkPVM>;

    deployContract(
      name: "IERC20Precompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Precompile>;
    deployContract(
      name: "IPVM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPVM>;
    deployContract(
      name: "IXcm",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXcm>;
    deployContract(
      name: "PVMark",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PVMark>;
    deployContract(
      name: "PVMarkPVM",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PVMarkPVM>;

    deployContract(
      name: "IERC20Precompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Precompile>;
    deployContract(
      name: "IPVM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IPVM>;
    deployContract(
      name: "IXcm",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IXcm>;
    deployContract(
      name: "PVMark",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PVMark>;
    deployContract(
      name: "PVMarkPVM",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.PVMarkPVM>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
