/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PVMarkInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hashLeafRust"
      | "hashLeafSol"
      | "hashPairRust"
      | "hashPairSol"
      | "rustContract"
      | "verifyProofRust"
      | "verifyProofSol"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "BenchmarkResult" | "BenchmarkRun"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "hashLeafRust",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashLeafSol",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashPairRust",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hashPairSol",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rustContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProofRust",
    values: [BytesLike, BytesLike, [BytesLike, BytesLike, BytesLike, BytesLike]]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProofSol",
    values: [BytesLike, BytesLike, [BytesLike, BytesLike, BytesLike, BytesLike]]
  ): string;

  decodeFunctionResult(
    functionFragment: "hashLeafRust",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashLeafSol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPairRust",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashPairSol",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rustContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProofRust",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProofSol",
    data: BytesLike
  ): Result;
}

export namespace BenchmarkResultEvent {
  export type InputTuple = [
    user: AddressLike,
    root: BytesLike,
    verified: boolean
  ];
  export type OutputTuple = [user: string, root: string, verified: boolean];
  export interface OutputObject {
    user: string;
    root: string;
    verified: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BenchmarkRunEvent {
  export type InputTuple = [fnName: string, gasUsed: BigNumberish];
  export type OutputTuple = [fnName: string, gasUsed: bigint];
  export interface OutputObject {
    fnName: string;
    gasUsed: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PVMark extends BaseContract {
  connect(runner?: ContractRunner | null): PVMark;
  waitForDeployment(): Promise<this>;

  interface: PVMarkInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hashLeafRust: TypedContractMethod<[leaf: BytesLike], [string], "view">;

  hashLeafSol: TypedContractMethod<[leaf: BytesLike], [string], "view">;

  hashPairRust: TypedContractMethod<
    [left: BytesLike, right: BytesLike],
    [string],
    "view"
  >;

  hashPairSol: TypedContractMethod<
    [left: BytesLike, right: BytesLike],
    [string],
    "view"
  >;

  rustContract: TypedContractMethod<[], [string], "view">;

  verifyProofRust: TypedContractMethod<
    [
      root: BytesLike,
      leaf: BytesLike,
      proof: [BytesLike, BytesLike, BytesLike, BytesLike]
    ],
    [boolean],
    "nonpayable"
  >;

  verifyProofSol: TypedContractMethod<
    [
      root: BytesLike,
      leaf: BytesLike,
      proof: [BytesLike, BytesLike, BytesLike, BytesLike]
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hashLeafRust"
  ): TypedContractMethod<[leaf: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hashLeafSol"
  ): TypedContractMethod<[leaf: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hashPairRust"
  ): TypedContractMethod<[left: BytesLike, right: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hashPairSol"
  ): TypedContractMethod<[left: BytesLike, right: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "rustContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyProofRust"
  ): TypedContractMethod<
    [
      root: BytesLike,
      leaf: BytesLike,
      proof: [BytesLike, BytesLike, BytesLike, BytesLike]
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProofSol"
  ): TypedContractMethod<
    [
      root: BytesLike,
      leaf: BytesLike,
      proof: [BytesLike, BytesLike, BytesLike, BytesLike]
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "BenchmarkResult"
  ): TypedContractEvent<
    BenchmarkResultEvent.InputTuple,
    BenchmarkResultEvent.OutputTuple,
    BenchmarkResultEvent.OutputObject
  >;
  getEvent(
    key: "BenchmarkRun"
  ): TypedContractEvent<
    BenchmarkRunEvent.InputTuple,
    BenchmarkRunEvent.OutputTuple,
    BenchmarkRunEvent.OutputObject
  >;

  filters: {
    "BenchmarkResult(address,bytes32,bool)": TypedContractEvent<
      BenchmarkResultEvent.InputTuple,
      BenchmarkResultEvent.OutputTuple,
      BenchmarkResultEvent.OutputObject
    >;
    BenchmarkResult: TypedContractEvent<
      BenchmarkResultEvent.InputTuple,
      BenchmarkResultEvent.OutputTuple,
      BenchmarkResultEvent.OutputObject
    >;

    "BenchmarkRun(string,uint256)": TypedContractEvent<
      BenchmarkRunEvent.InputTuple,
      BenchmarkRunEvent.OutputTuple,
      BenchmarkRunEvent.OutputObject
    >;
    BenchmarkRun: TypedContractEvent<
      BenchmarkRunEvent.InputTuple,
      BenchmarkRunEvent.OutputTuple,
      BenchmarkRunEvent.OutputObject
    >;
  };
}
