/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface PVMarkPVMInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "hashChain"
      | "hashLeaf"
      | "hashPair"
      | "matrixMul"
      | "modExp"
      | "pairingLoop"
      | "verifyProof"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "hashChain",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "hashLeaf", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "hashPair",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matrixMul",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "modExp",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pairingLoop",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProof",
    values: [BytesLike, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "hashChain", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashLeaf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hashPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matrixMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "modExp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pairingLoop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProof",
    data: BytesLike
  ): Result;
}

export interface PVMarkPVM extends BaseContract {
  connect(runner?: ContractRunner | null): PVMarkPVM;
  waitForDeployment(): Promise<this>;

  interface: PVMarkPVMInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  hashChain: TypedContractMethod<
    [seed: BytesLike, rounds: BigNumberish],
    [string],
    "view"
  >;

  hashLeaf: TypedContractMethod<[leaf: BytesLike], [string], "view">;

  hashPair: TypedContractMethod<
    [left: BytesLike, right: BytesLike],
    [string],
    "view"
  >;

  matrixMul: TypedContractMethod<[n: BigNumberish], [bigint], "view">;

  modExp: TypedContractMethod<
    [base: BigNumberish, exp: BigNumberish, mod: BigNumberish],
    [bigint],
    "view"
  >;

  pairingLoop: TypedContractMethod<[rounds: BigNumberish], [bigint], "view">;

  verifyProof: TypedContractMethod<
    [leaf: BytesLike, proof: BytesLike[], root: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "hashChain"
  ): TypedContractMethod<
    [seed: BytesLike, rounds: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "hashLeaf"
  ): TypedContractMethod<[leaf: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "hashPair"
  ): TypedContractMethod<[left: BytesLike, right: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "matrixMul"
  ): TypedContractMethod<[n: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "modExp"
  ): TypedContractMethod<
    [base: BigNumberish, exp: BigNumberish, mod: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "pairingLoop"
  ): TypedContractMethod<[rounds: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifyProof"
  ): TypedContractMethod<
    [leaf: BytesLike, proof: BytesLike[], root: BytesLike],
    [boolean],
    "view"
  >;

  filters: {};
}
