/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC20Precompile,
  IERC20PrecompileInterface,
} from "../IERC20Precompile";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "beneficiary",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC20Precompile__factory {
  static readonly abi = _abi;
  static createInterface(): IERC20PrecompileInterface {
    return new Interface(_abi) as IERC20PrecompileInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC20Precompile {
    return new Contract(address, _abi, runner) as unknown as IERC20Precompile;
  }
}
