/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { PVMarkPVM, PVMarkPVMInterface } from "../PVMarkPVM";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leaf",
        type: "bytes32",
      },
    ],
    name: "hashLeaf",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "left",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "right",
        type: "bytes32",
      },
    ],
    name: "hashPair",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "leaf",
        type: "bytes32",
      },
      {
        internalType: "bytes32[]",
        name: "proof",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32",
        name: "root",
        type: "bytes32",
      },
    ],
    name: "verifyProof",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102df806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c80633695a9401461004657806358161a421461006c5780635d5eee4a1461008f575b600080fd5b6100596100543660046101d3565b6100a2565b6040519081526020015b60405180910390f35b61007f61007a3660046101f5565b6100fd565b6040519015158152602001610063565b61005961009d36600461027a565b6101a1565b6000818310156100de5760408051602081018590529081018390526060015b6040516020818303038152906040528051906020012090506100f7565b60408051602081018490529081018490526060016100c1565b92915050565b600084815b8481101561019557600086868381811061011e5761011e610293565b90506020020135905080831161015f57604080516020810185905290810182905260600160405160208183030381529060405280519060200120925061018c565b60408051602081018390529081018490526060016040516020818303038152906040528051906020012092505b50600101610102565b50909114949350505050565b6000816040516020016101b691815260200190565b604051602081830303815290604052805190602001209050919050565b600080604083850312156101e657600080fd5b50508035926020909101359150565b6000806000806060858703121561020b57600080fd5b84359350602085013567ffffffffffffffff8082111561022a57600080fd5b818701915087601f83011261023e57600080fd5b81358181111561024d57600080fd5b8860208260051b850101111561026257600080fd5b95986020929092019750949560400135945092505050565b60006020828403121561028c57600080fd5b5035919050565b634e487b7160e01b600052603260045260246000fdfea2646970667358221220cb6583a7669befdc7cb09383e5e3ed9d9e117c4df92eeb25e61e35d8460c09d064736f6c63430008180033";

type PVMarkPVMConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PVMarkPVMConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PVMarkPVM__factory extends ContractFactory {
  constructor(...args: PVMarkPVMConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      PVMarkPVM & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): PVMarkPVM__factory {
    return super.connect(runner) as PVMarkPVM__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PVMarkPVMInterface {
    return new Interface(_abi) as PVMarkPVMInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): PVMarkPVM {
    return new Contract(address, _abi, runner) as unknown as PVMarkPVM;
  }
}
